config/routes.rb
Manager::Application.routes.draw do
  devise_for :users

  resources :orders do
    post :add_box, :on => :member
  end

  resources :boxes

  get "widgets/filter"

  resources :widgets

  get "inventory/new"

  get "about/company"
  get "about/contact"

  match "/products/:name" => "widgets#show", :as => :products

  root :to => "widgets#index"
end

app/models/box.rb
class Box < ActiveRecord::Base
  attr_accessible :color, :material, :order_id
  belongs_to :order
  has_one :widget
end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
before_filter :set_box, only: %w(show edit update destroy)
  # GET /boxes
  # GET /boxes.json
  def index
    @boxes = Box.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @boxes }
    end
  end

  # GET /boxes/1
  # GET /boxes/1.json
  def show
    @box = Box.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @box }
    end
  end

  # GET /boxes/new
  # GET /boxes/new.json
  def new
    @box = Box.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @box }
    end
  end

  # GET /boxes/1/edit
  def edit
  end

  # POST /boxes
  # POST /boxes.json
  def create
    @box = Box.new(params[:box])

    respond_to do |format|
      if @box.save
        format.html { redirect_to @box, notice: 'Box was successfully created.' }
        format.json { render json: @box, status: :created, location: @box }
      else
        format.html { render action: "new" }
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /boxes/1
  # PUT /boxes/1.json
  def update
    @box = Box.find(params[:id])

    respond_to do |format|
      if @box.update_attributes(params[:box])
        format.html { redirect_to @box, notice: 'Box was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boxes/1
  # DELETE /boxes/1.json
  def destroy
    @box.destroy

    respond_to do |format|
      format.html { redirect_to(boxes_url) }
      format.json { head :ok }
    end
  end

  private

  def set_box
    @box = Box.find{params[:id]}
  end


end

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/views/boxes/_form.html.erb
<%= form_for(@box) do |f| %>
  <% if @box.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@box.errors.count, "error") %> prohibited this box from being saved:</h2>

      <ul>
      <% @box.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :material %><br />
    <%= f.text_field :material %>
  </div>
  <div class="field">
    <%= f.label :color %><br />
    <%= f.text_field :color %>
  </div>
  <div class="actions">
    <%= f.submit 'Create Box', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/boxes/edit.html.erb
<h1>Editing box</h1>

<%= render 'form' %>

<%= link_to 'Show', @box, class: "btn btn-small" %> |
<%= link_to 'Back', boxes_path, class: "btn btn-small" %>

app/views/boxes/index.html.erb
<div class="page-header"><h2>Listing Boxes  <small>Rails is Awesome</small></h2></div>

<table class="listing table table-striped table-bordered table-hover">
  <tr>
    <th>Material</th>
    <th>Color</th>
    <th>Widget</th>
    <th colspan="3">Actions</th>
  </tr>

<% @boxes.each do |box| %>
  <tr>
    <td><%= box.material %></td>
    <td><%= box.color %></td>
    <td><%= box.widget ? box.widget.name : "None" %></td>
    <td><%= link_to 'Show', box, class: "btn btn-success btn-small" %></td>
    <td><%= link_to 'Edit', edit_box_path(box), class: "btn btn-warning btn-small" %></td>
    <td><%= link_to 'Destroy', box, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-small" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Box', new_box_path, class: "btn btn-large btn-block pull-center" %>

app/views/boxes/new.html.erb
<h1>New box</h1>

<%= render 'form' %>

<%= link_to 'Back', boxes_path, class: "btn btn-small" %>

app/views/boxes/show.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success"><%= notice %></div>
<% end %>

<div class="page-header"><h2><%= "Material: #{@box.material} " %><small>Rails is Awesome</small></h2></div>

<p>
  <b>Material:</b>
  <%= @box.material %>
</p>

<p>
  <b>Color:</b>
  <%= @box.color %>
</p>


<%= link_to 'Back', boxes_path, class: "btn btn-small" %> | <%= link_to 'Edit', edit_box_path(@box), class: "btn btn-small" %>