config/routes.rb
Manager::Application.routes.draw do
  devise_for :users

  resources :orders do
    post :add_box, :on => :member
  end

  resources :boxes

  get "widgets/filter"

  resources :widgets

  get "inventory/new"

  get "about/company"
  get "about/contact"

  match "/products/:name" => "widgets#show", :as => :products

  root :to => "widgets#index"
end

app/models/widget.rb
class Widget < ActiveRecord::Base
  attr_accessible :color, :description, :name, :size, :box_id
  belongs_to :box
  validates :name, :presence => true
  validates_length_of :name, minimum: 3
  validates :size, numericality: true		
end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  # GET /products/Fire Gasket
  # GET /widgets
  # GET /widgets.json
  def index
    @widgets = Widget.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @widgets }
    end
  end

  # GET /widgets/1
  # GET /widgets/1.json
  def show
    if params[:name]
      @widget = Widget.find_by_name(params[:name])
    else
      @widget = Widget.find(params[:id])
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @widget }
    end
  end

  # GET /widgets/new
  # GET /widgets/new.json
  def new
    @widget = Widget.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @widget }
    end
  end

  # GET /widgets/1/edit
  def edit
    @widget = Widget.find(params[:id])
  end

  # POST /widgets
  # POST /widgets.json
  def create
    @widget = Widget.new(params[:widget])

    respond_to do |format|
      if @widget.save
        Notifications.widget_creation(@widget).deliver
        format.html { redirect_to @widget, notice: 'Widget was successfully created.' }
        format.xml {render xml: @widget, status: :created, location: @widget}
      else
        format.html { render action: "new" }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /widgets/1
  # PUT /widgets/1.json
  def update
    @widget = Widget.find(params[:id])

    respond_to do |format|
      if @widget.update_attributes(params[:widget])
        format.html { redirect_to @widget, notice: 'Widget was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /widgets/1
  # DELETE /widgets/1.json
  def destroy
    @widget = Widget.find(params[:id])
    @widget.destroy

    respond_to do |format|
      format.html { redirect_to widgets_url }
      format.json { head :no_content }
    end
  end

  def filter
    @boxes = Box.where(material: params[:size])
    if @boxes.count > 0 
      respond_to do |format|
        format.html { render template: "boxes/index" }
      end
    else
      @widgets = Widget.where(size: params[:size])

      respond_to do |format|
        format.html { render action: "index" }
      end
    end
  end
end

app/helpers/widgets_helper.rb
module WidgetsHelper
	def box_options
		Box.all.collect {|b| [b.color, b.id]}
	end
end

app/views/widgets/_form.html.erb
<%= form_for(@widget) do |f| %>
  <% if @widget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@widget.errors.count, "error") %> prohibited this widget from being saved:</h2>

      <ul>
      <% @widget.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :size => "20x5" %>
  </div>
  <div class="field">
    <%= f.label :color %><br />
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :size %><br />
    <%= f.number_field :size %>
  </div>
  <div class="field">
    <%= f.label :box_id, "box" %><br />
    <%= f.select :box_id, box_options, {:include_blank => true} %>
  </div>

  <div class="actions">

    <%= f.submit 'Submit', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/widgets/edit.html.erb
<h1>Editing widget</h1>

<%= render 'form' %>

<%= link_to 'Show', @widget, class: "btn btn-small" %> |
<%= link_to 'Back', widgets_path, class: "btn btn-small" %>

app/views/widgets/index.html.erb
<div class="page-header"><h2>Listing Widgets  <small>Rails is Awesome</small></h2></div>

<table class= "listing table table-striped table-bordered table-hover">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Color</th>
    <th>Size</th>
    <th>Box</th>
    <th colspan="3">Actions</th>
    <th>Created</th>
  </tr>

<% @widgets.each do |widget| %>
  <tr>
    <td><%= widget.name %></td>
    <td><%= widget.description %></td>
    <td><%= widget.color %></td>
    <td><%= widget.size %></td>
    <td><%= widget.box ? widget.box.material : "None" %></td> 
    <td><%= link_to 'Show', widget, class: "btn btn-success btn-small" %></td>
    <td><%= link_to 'Edit', edit_widget_path(widget), class: "btn btn-warning btn-small" %></td>
    <td><%= link_to 'Destroy', widget, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-small"%></td>
    <td style="font-style:italic;font-weight:600;color:#696969"><%= "#{time_ago_in_words(widget.created_at)} ago" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Widget', new_widget_path, class: "btn btn-large btn-block pull-center" %>

app/views/widgets/new.html.erb
<h1>New widget</h1>

<%= render 'form' %>

<%= link_to 'Back', widgets_path, class: "btn btn-small" %>

app/views/widgets/show.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success"><%= notice %></div>
<% end %>

<div class="page-header"><h2><%= "Widget: #{@widget.name}  " %><small>Rails is Awesome</small></h2></div>

<p>
  <b>Description:</b>
  <%= @widget.description %>
</p>

<p>
  <b>Color:</b>
  <%= @widget.color %>
</p>

<p>
  <b>Size:</b>
  <%= @widget.size %>
</p>

<p>
	<b>Box:</b>
	<%= @widget.box ? @widget.box.material : "None" %>
</p>

<%= link_to 'Back', widgets_path, class: "btn btn-small" %> | <%= link_to 'Edit', edit_widget_path(@widget), class: "btn btn-small" %>