config/routes.rb
Manager::Application.routes.draw do
  devise_for :users

  resources :orders do
    post :add_box, :on => :member
  end

  resources :boxes

  get "widgets/filter"

  resources :widgets

  get "inventory/new"

  get "about/company"
  get "about/contact"

  match "/products/:name" => "widgets#show", :as => :products

  root :to => "widgets#index"
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :name
  has_many :boxes
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/new
  # GET /orders/new.json
  def new
    @order = Order.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(params[:order])

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render json: @order, status: :created, location: @order }
      else
        format.html { render action: "new" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /orders/1
  # PUT /orders/1.json
  def update
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end

  #POST /add_box/1?box_id=1
  def add_box
    @order = Order.find(params[:id])
    @box = Box.find(params[:box_id])

    respond_to do |format|
      if !@order.boxes.include?(@box) && @order.boxes << @box
        flash[:notice] = "Box was successfully added to order!"
        format.html {redirect_to(@order)}
        format.json {head :ok}
        format.js
      else
        format.html {render action:"edit"}
        format.json {render json: @order.errors, status: :unprocessable_entity}
      end
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_box.html.erb
<li id="box_<%= box.id %>">A <%= box.color %> <%= box.material %> box.</li>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit 'Create Order', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/orders/_total.html.erb
<p>Order Contains <%= pluralize(@order.boxes.size, 'box') %></p>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order, class: "btn btn-small" %> |
<%= link_to 'Back', orders_path, class: "btn btn-small" %>

app/views/orders/index.html.erb
<div class="page-header"><h2>Listing Orders  <small>Rails is Awesome</small></h2></div>

<table class="listing table table-striped table-bordered table-hover">
  <tr>
    <th>Name</th>
    <th>Placed on</th>
    <th colspan="3">Actions</th>
  </tr>

<% @orders.each do |order| %>
  <tr>
    <td><%= order.name %></td>
    <td style="font-style:italic;font-weight:600;color:#696969"><%= big_date(order.created_at) %></td>
    <td><%= link_to 'Show', order, class: "btn btn-success btn-small" %></td>
    <td><%= link_to 'Edit', edit_order_path(order), class: "btn btn-warning btn-small" %></td>
    <td><%= link_to 'Destroy', order, confirm: 'Are you sure?', method: :delete, class: "btn btn-danger btn-small" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Order', new_order_path, class: "btn btn-large btn-block pull-center" %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path, class: "btn btn-small" %>

app/views/orders/show.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success"><%= notice %></div>
<% end %>

<div class="page-header"><h2><%= "Order: #{@order.name}  " %><small>Rails is Awesome</small></h2></div>

<p>
  <b>Placed on:</b>
  <%= @order.created_at %>
</p>
<div id="total">
	<%= render partial: 'total' %>
</div>

<ul id="box_listing">
	<% @order.boxes.each do |box| %>
		<%= render partial: 'box', locals: {box: box} %>
	<% end %>
</ul>

<p>Add a box to this order:</p>

<%= form_tag add_box_order_path(@order), remote: true do %>
	<label for="box_order">Box</label><br/>
	<%= select_tag 'box_id', options_for_select(Box.find(:all).collect { |b| [b.material, b.id] }), style: "margin-top:10px;" %>
	<%= submit_tag 'Add Box', class: "btn btn-primary" %>
<% end %>


<%= link_to 'Back', orders_path, class: "btn btn-small" %> | <%= link_to 'Edit', edit_order_path(@order), class: "btn btn-small" %>